name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: './windows-95-svelte/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./windows-95-svelte

      - name: Build
        env:
          BASE_PATH: '/windows-95-svelte'
        run: npm run build
        working-directory: ./windows-95-svelte

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './windows-95-svelte/build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4